from .addtocart_view import AddToCartView
from .mycart_view import MyCartView
from .removefromcart_view import RemoveFromCartView
from .clearcart_view import ClearCartView
from .checkout_view import CheckOutView
from .modifyquantity_view import ModifyQuantityView
from .categoryitems_view import CategoryItemsView
from .resturantitems_view import ResturantItemsView
from .userhome_view import UserHomeView
from .myorders_view import MyOrdersView
from .orderdetail_view import OrderDetailView
from .popularitem_view import PopularItemView
from .itemdetail_view import ItemDetailView
