# Generated by Django 4.2.8 on 2024-01-02 08:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="photo"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="resturant",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
