# Generated by Django 4.2.8 on 2024-01-03 08:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_category_name_alter_item_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="photo"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status_changed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
