# Generated by Django 4.2.8 on 2024-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_item_photo_alter_order_status_changed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="stprice",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
