# Generated by Django 4.2.8 on 2023-12-28 08:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_cartitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="photo"
            ),
        ),
    ]
