# Generated by Django 4.2.8 on 2023-12-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_item_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="retired",
            field=models.BooleanField(default=False),
        ),
    ]
