# Generated by Django 4.2.8 on 2023-12-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_cartitem_stprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
