# Generated by Django 4.2.8 on 2023-12-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_order_status_changed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.item"
            ),
        ),
    ]
