# Generated by Django 4.2.8 on 2024-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_alter_user_display_name_alter_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
