from .adminorderdashboard_view import AdminOrderDashboardView
from .categorycreate_view import CategoryCreateView
from .categoryupdate_view import CategoryUpdateView
from .itemcreate_view import ItemCreateView
from .itemupdate_view import ItemUpdateView
from .resturantcreate_view import ResturantCreateView
from .resturantupdate_view import ResturantUpdateView
from .dashboard_view import DashboardView
from .filterorder_view import FilterOrderView
from .modifyorder_view import ModifyOrderView
from .orderdetail_view import OrderDetailView
